apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-icda
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-icda@sha256:47c95b9c2e934f3445b498b50650ba1ec6b3d148c5e014f47a459280d4c6589f
        name: my-nodejs
        resources: {}
status: {}
